version: '3'
services:
  tls:
    image: nginx:1.15.5
    ports:
      - "14500:443"
    depends_on:
      - application
    volumes:
      - "./tls.conf:/etc/nginx/conf.d/default.conf"
      - "./tls_cert.pem:/etc/nginx/tls_cert.pem"
      - "./tls_key.pem:/etc/nginx/tls_key.pem"
  application:
    image: postgrest/postgrest
    ports:
      - "14501:3000"
    links:
      - database:db
    environment:
      PGRST_JWT_AUD: ${JWT_APP_ID}
      # Only necessary if using the `HS256` JsonWebToken signature algorithm
      PGRST_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - database
    volumes:
      - "./postgrest.conf:/etc/postgrest.conf"
      # Only necessary if using the `RS256` JsonWebToken signature algorithm
      - "./token_signing_pubkey.jwk:/etc/auth0_pubkey.jwk"
  database:
    image: postgres:11.0
    ports:
      - "14503:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "14502:8080"
#    expose:
#      - "8080"
    environment:
      API_URL: http://localhost:3000/
